name: Build and Deploy Flutter Web to Vercel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Flutter pub get
        run: flutter pub get

      - name: Create .env for flutter_dotenv
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          PAYMENT_API_BASE_URL: ${{ secrets.PAYMENT_API_BASE_URL }}
          RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
          DEBUG_PAYMENTS: ${{ secrets.DEBUG_PAYMENTS }}
        run: |
          cat > .env <<EOF
          SUPABASE_URL=${SUPABASE_URL}
          SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
          API_BASE_URL=${API_BASE_URL}
          PAYMENT_API_BASE_URL=${PAYMENT_API_BASE_URL}
          RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
          DEBUG_PAYMENTS=${DEBUG_PAYMENTS}
          EOF
          ls -la .env

      - name: Build Flutter web
        run: flutter build web --release

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod ./build/web --token $VERCEL_TOKEN --confirm --name srcarehive-web
